language: node_js
node_js:
  - "7"

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo generate
  
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  repo: Joing2046/Joing2046.github.io
  target_branch: master
  email: joing2046@163.com
  name: joing
  on:
    branch: src

branches:
  only:
    - src